export const FETCH_ALL_BREEDS = 'FETCH_ALL_BREEDS';
export const FETCH_ALL_BREEDS_DONE = 'FETCH_ALL_BREEDS_DONE';
export const FETCH_ALL_BREEDS_ERROR = 'FETCH_ALL_BREEDS_ERROR';
export const FETCH_BREED_IMAGES = 'FETCH_BREED_IMAGES';
export const FETCH_BREED_IMAGES_DONE = 'FETCH_BREED_IMAGES_DONE';
export const FETCH_BREED_IMAGES_ERROR = 'FETCH_BREED_IMAGES_ERROR';
export const SELECT_BREED = 'SELECT_BREED';
